### PR TITLE
fix NULL pointer dereference, backport A-MSDU fixes for Raspberry Pi,  RSSI, Frame Control, Phy Bits, etc

### PR DESCRIPTION
**Pull request by mzakharo**
After I added the NULL pointer check, I monitored the log, and indeed, this check is happening sometimes. Also, A-MSDU skip helps Raspberry pi stay up without trapping.

### CODE REVIEW

**Comment by tweigel-dev** [comment]
great work! why this PR don't get any attention ?

**Comment by maurovm** [comment]
Excellent work Mikhail. Your changes fixed my problems. Check #177.

I vote for the authors of nexmon_csi to merge your pull request.

**Comment by Colin-Guolin** [comment]
Hi @mzakharo 

I am using your pull request to obtain the RSSI value using Raspberry pi, but I found some problem with my data, the CSI value of the subcarrier from 28 to 35 are constant. (The subcarrier index range from 0 to 63)
image
I am not sure where this problem comes from, have you got the same problem?

**Comment by mzakharo** [comment]
> Hi @mzakharo
> 
> I am using your pull request to obtain the RSSI value using Raspberry pi, but I found some problem with my data, the CSI value of the subcarrier from 28 to 35 are constant. (The subcarrier index range from 0 to 63)
> image
> I am not sure where this problem comes from, have you got the same problem?

I am assuming bandwidth of your capture is 20Mhz.  For whatever reason, on 20MHz bandwidth, carriers 28-35 have no valid data, this behaviour has nothing to do with this patch, and occurs on master branch.  if you inspect data more closely, you still get the expected valid 52 complex values from other points in the CSI vector.

**Comment by Colin-Guolin** [comment]
> > Hi @mzakharo
> > I am using your pull request to obtain the RSSI value using Raspberry pi, but I found some problem with my data, the CSI value of the subcarrier from 28 to 35 are constant. (The subcarrier index range from 0 to 63)
> > image
> > I am not sure where this problem comes from, have you got the same problem?
> 
> I am assuming bandwidth of your capture is 20Mhz. For whatever reason, on 20MHz bandwidth, carriers 28-35 have no valid data, this behaviour has nothing to do with this patch, and occurs on master branch. if you inspect data more closely, you still get the expected valid 52 complex values from other points in the CSI vector.

Thanks for replying, I have checked the data from the master branch, indeed, the carriers 28-35 have no valid data. I just realised that they are corresponding to the null subcarrier in OFDM.

**Comment by haochenku** [comment]
Hi @mzakharo  The frame control information from my side does not look good. It changes a lot. Also I was expecting frame control from different cores should be same, but actually they are not. Could you have a look? 
image

**Comment by mzakharo** [comment]
Frame control is added only for raspberry pi. You need the equivalent
assembly for your platform

**Comment by haochenku** [comment]
thank you so much ! any guidance or reference on how to proceed ?

**Comment by mzakharo** [comment]
Raspberry pi patch is your reference. Good luck

**Comment by haochenku** [comment]
THank you. BTW, in the multiple core and stream case, could we assume that
the csi from core 0 always comes before csi from core 1?

**Comment by mzakharo** [comment]
For the most part yes. But i would not count on it. Werid things happen
from time to time.

**Comment by haochenku** [comment]
I see. Thank you. Is there any reliable way to distinguish the core 0 and
core 1 on from the same frame? Will time difference be good?

**Comment by mzakharo** [comment]
I don't know of any. My strategy has been to drop frames that are out of
order

**Comment by CDeLeon94** [comment]
The reference file mentioned for decoding the phybits has been removed
(https://github.com/MerlinRdev/86u-merlin/blob/master/release/src-rt-5.02hnd/bcmdrivers/broadcom/net/wl/impl51/4365/src/include/d11.h#L2935)

Is there any other source that has this information?

**Comment by mzakharo** [comment]
> The reference file mentioned for decoding the phybits has been removed (https://github.com/MerlinRdev/86u-merlin/blob/master/release/src-rt-5.02hnd/bcmdrivers/broadcom/net/wl/impl51/4365/src/include/d11.h#L2935)
> 
> Is there any other source that has this information?

https://github.com/RMerl/asuswrt-merlin.ng/blob/6b60627c8c9c5c0271e956c914afb5277f81f9c4/release/src-rt-6.x.4708/include/d11.h#L2517
Most useful for CSI decoding is   PRXS0_ACPHY_SUBBAND_MASK

**Pull request closed without merging**
