### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Adam-Antios**
Updated procedure for the build and installation of the Nexmon CSI. Fixed a few dependencies and added a way to get the correct kernel headers.

### CODE REVIEW

**Comment by zeroby0** [comment]
This is a good PR. I doubt they'll merge it, but here are some suggestions I have:

1. Move the makecsiparams building step to Raspberry Pi section.
    * Building it needs the environmental variables set when building Nexmon.
    * The process to build it is different in different platforms. On the RT-AC86u routers, for example, you'll have to cross compile it.
    * You can even link it from `/usr/bin/mcp` so that it's in `PATH`, and is shorter to type.
2. The second example for makecsiparams seems to be exactly the same as the first example, except for the `./` part. Maybe you could remove it, or use only the `-c157/80 -C 1 -N 1` flags to emphasize that `-m` and `-b` flags are optional?
3. The `rpi-source` part is nice. I don't think it will be merged because support for 5.10 will arrive at some point and they will have to change this again.

Also, if you find yourself building Nexmon_csi repeatedly, I have a script here to automate the process. https://github.com/nexmonster/nexmon_csi/tree/pi-4.19.97.

**Comment by Adam-Antios** [comment]
@zeroby0 Greetings! Because I need to keep installing it, I made my own script too, but thanks for the offer! About the merging, I see no reason why they wouldn't merge it given that it is practically impossible for Nexmon CSI in its current state to be installed , at least, on Raspberry Pi.

Regarding your points, the instructions I added were placed where they are needed if you try to build and install Nexmon from the start. Moreover I think it is nice to be explicit about certain things as to avoid unnecessary confusion. Also support for 5.10 may come, but they will still need to maintain information about people running older versions, so they wouldn't need to change what I wrote at all.

Concluding, my point is that people need to follow the steps I appended if they wish to build and install Nexmon CSI. This information is not optional. You can't install it without it, at least, as I mentioned, on Raspberry Pi. So they actually have to merge it.

**Comment by zeroby0** [comment]
> I see no reason why they wouldn't merge it

Not one PR has been merged in the history of this repo 😂. Even the awesome #46.
The maintainers are really busy, so it's to be expected. I'm not even half as busy, and even I have backlogs on work to be done on my fork, so they are not at fault at all.

But I do hope it gets merged. Thanks for your work :)

**Comment by Adam-Antios** [comment]
You are right I guess. Thank you very much for your helpful comments before. :)

**Comment by Adam-Antios** [comment]
> This is a good PR. I doubt they'll merge it, but here are some suggestions I have:
> 
> 1. Move the makecsiparams building step to Raspberry Pi section.
>    
>    * Building it needs the environmental variables set when building Nexmon.
>    * The process to build it is different in different platforms. On the RT-AC86u routers, for example, you'll have to cross compile it.
>    * You can even link it from `/usr/bin/mcp` so that it's in `PATH`, and is shorter to type.
> 2. The second example for makecsiparams seems to be exactly the same as the first example, except for the `./` part. Maybe you could remove it, or use only the `-c157/80 -C 1 -N 1` flags to emphasize that `-m` and `-b` flags are optional?
> 3. The `rpi-source` part is nice. I don't think it will be merged because support for 5.10 will arrive at some point and they will have to change this again.
> 
> Also, if you find yourself building Nexmon_csi repeatedly, I have a script here to automate the process. https://github.com/nexmonster/nexmon_csi/tree/pi-4.19.97.
> 
> **Edit**: Since I didn't see it mentioned in your Readme, I'm assuming you don't use this yet: You can set the patched firmware to be automatically loaded on reboot instead of the original WiFi driver - https://github.com/nexmonster/nexmon_csi/blob/pi-4.19.97/install.sh#L62

**Comment by Adam-Antios** [comment]
@zeroby0 I tried using your installation script with the correct Rasbian OS and kernel on the Raspberry Pi Model 3 B+ but it deactivates the wlan0 interface and it can't be brought up again, so I can't use it. Do you have any idea why is that?

**Review by matthiasseemoo — CHANGES_REQUESTED** [review]
PR https://github.com/seemoo-lab/nexmon_csi/pull/255 is now merged, so the readme needs some updates again to reflect this.

**Pull request closed without merging**
